dictionaries = ["en_us"]
words = [
    "emscripten",
    "SRCS",
    "CFLAGS",
    "CXX",
    "Wno",
    "fno",
    "rtti",
    "malloc",
    "ccall",
    "cwrap",
    "libbid",
    "mkdir",
    "emcc",
    "iml",
    "RND",
    "xvfz",
    "blitter",
    "powerdown",
    "clk",
    "chrono"
]
ignore_patterns = ["D[A-Z]+", "<.*>"]
